<?php
namespace app\modules\ful\controllers;
use app\compents\CQueryParamAuth;
use app\models\ApiReturn;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\web\Response;
use yii\filters\ContentNegotiator;
use yii\web\Controller;

class BaseController extends Controller
{
    public $modelClass = 'app\models\Members';
    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items',
    ];
    /**
     * 返回数据
     * @var ApiReturn
     */
    protected $return;
    /**
     * params数据
     * @var array
     */
    protected $params = [];
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['contentNegotiator'] = [
            'class' => ContentNegotiator::className(),
            'formats' => [
                'application/json' => Response::FORMAT_JSON,

            ],
        ];
        $behaviors['authenticator'] = [
            'class' => CompositeAuth::className(),
            'authMethods' => [
                HttpBasicAuth::className(),
                HttpBearerAuth::className(),
                CQueryParamAuth::className(),
            ],
        ];
        return $behaviors;
    }
    /**
     * 初始化
     */
    public function init()
    {
        $this->return = ApiReturn::Instance();
        $this->params = \Yii::$app->request->queryParams;
        parent::init(); // TODO: Change the autogenerated stub
    }
}
